version: '3.7'
x-logging: &default-logging
    driver: journald
    options:
        tag: "{{.Name}}"

x-utility: &default-utility
    image: "alpine:3.11"
    logging: *default-logging
    network_mode: host

services:
        tor:
                image: getumbrel/tor:v0.4.1.9
                restart: on-failure
                logging: *default-logging
                volumes:
                    - "${PWD}/tor/torrc:/etc/tor/torrc"
                    - "${PWD}/tor/data:/var/lib/tor/"
                    - "${PWD}/tor/run:/var/run/tor/"
                networks:
                    net:
                        ipv4_address: 10.11.5.1
        nginx:
                image: nginx:1.17.8
                depends_on: [ tor ]
                logging: *default-logging
                volumes:
                        - ${PWD}/nginx:/etc/nginx
                restart: on-failure
                stop_grace_period: 30s
                ports:
                    - "80:80"
                networks:
                    net:
                        ipv4_address: 10.11.0.2
        bitcoin:
                image: lncm/bitcoind:v0.20.0
                depends_on: [ tor ]
                logging: *default-logging
                command: "-zmqpubrawblock=tcp://0.0.0.0:28332 -zmqpubrawtx=tcp://0.0.0.0:28333"
                volumes:
                        - ${PWD}/bitcoin:/root/.bitcoin
                        - ${PWD}/bitcoin:/data/.bitcoin
                        - ${PWD}/bitcoin:/data/bitcoin
                restart: on-failure
                stop_grace_period: 15m30s
                ports:
                    - "127.0.0.1:8333:8333"
                networks:
                    net:
                        ipv4_address: 10.11.1.1
        lnd:
                image: nolim1t/lnd:v0.10.1-experimental
                depends_on: [ tor ]
                logging: *default-logging
                volumes:
                        - ${PWD}/lnd:/data/.lnd
                        - ${PWD}/lnd:/root/.lnd
                        - ${PWD}/bitcoin:/root/.bitcoin
                restart: on-failure
                stop_grace_period: 5m30s
                networks:
                    net:
                        ipv4_address: 10.11.1.2
        dashboard:
                image: mayankchhabra/dashboard:ota
                depends_on: [ bitcoin, lnd, nginx ]
                logging: *default-logging
                restart: always
                stop_grace_period: 1m30s
                networks:
                    net:
                        ipv4_address: 10.11.0.3
        manager:
                image: mayankchhabra/manager:feature-ota
                depends_on: [ bitcoin, lnd, nginx ]
                logging: *default-logging
                restart: unless-stopped
                stop_grace_period: 5m30s
                volumes:
                        - ${PWD}/db:/db
                        - /var/run/docker.sock:/var/run/docker.sock
                        - /usr/bin/docker:/usr/bin/docker
                        - ${PWD}:${PWD}
                        - ${PWD}/update:/update
                environment:
                    PORT: "3006"
                    USER_PASSWORD_FILE: "/db/user.json"
                    JWT_PUBLIC_KEY_FILE: "/db/jwt-public-key/jwt.pem"
                    JWT_PRIVATE_KEY_FILE: "/db/jwt-private-key/jwt.key"
                    JWT_EXPIRATION: "3600"
                    DOCKER_COMPOSE_DIRECTORY: $PWD
                    DEVICE_HOST: "http://umbrel.local"
                    MIDDLEWARE_API_URL: "http://10.11.2.2"
                    UPDATE_URL: "https://raw.githubusercontent.com/mayankchhabra/umbrel-compose/feature-ota/update/version.json"
                    UPDATE_VERSION_FILE: "update/version.json"
                    UPDATE_STATUS_FILE: "update/status.json"
                    UPDATE_SIGNAL_FILE: "update/START"
                networks:
                    net:
                        ipv4_address: 10.11.2.1
        middleware:
                image: getumbrel/middleware:v0.1.1
                depends_on: [ bitcoin, lnd, nginx ]
                command: ["./wait-for-node-manager.sh", "10.11.2.1", "npm", "start"]
                logging: *default-logging
                restart: unless-stopped
                depends_on: [ manager ]
                volumes:
                        - ${PWD}/lnd:/lnd
                        - ${PWD}/db/jwt-public-key:/jwt-public-key
                environment:
                    PORT: "3005"
                    BITCOIN_HOST: "10.11.1.1"
                    RPC_PORT: "RPCPORT"
                    RPC_USER: "lncm"
                    RPC_PASSWORD: "RPCPASS"
                    LND_NETWORK: "regtest"
                    LND_HOST: "10.11.1.2"
                    JWT_PUBLIC_KEY_FILE: "/jwt-public-key/jwt.pem"
                    DEVICE_HOST: "http://umbrel.local"
                networks:
                    net:
                        ipv4_address: 10.11.2.2
networks:
    net:
        ipam:
            driver: default
            config:
                - subnet: 10.11.0.0/16
