#!/bin/sh

set -e

STATE="$1"
FILES="$2"

pre_install_script="$FILES"/files/pre-install.sh
install_script="$FILES"/files/install.sh
post_install_script="$FILES"/files/post-install.sh
checks_script="$FILES"/files/checks.sh
error_script="$FILES"/files/on-error.sh
success_script="$FILES"/files/on-success.sh

case "$STATE" in

    NeedsArtifactReboot)
        echo "No"
    ;;

    SupportsRollback)
        echo "Yes"
    ;;

    ArtifactInstall_Enter)
        chmod u+x $pre_install_script
        $pre_install_script
    ;;

    ArtifactInstall)
        chmod u+x $install_script
        $install_script
    ;;

    ArtifactInstall_Leave)
        chmod u+x $post_install_script
        $post_install_script
    ;;

    ArtifactCommit_Enter)
        chmod u+x $checks_script
        $checks_script
    ;;

    ArtifactCommit)
        chmod u+x $success_script
        $success_script
    ;;

    ArtifactRollback)
        chmod u+x $error_script
        $error_script
    ;;

esac

exit 0