#!/bin/sh

set -e

STATE="$1"
FILES="$2"

pre_install_script="$FILES"/files/pre-install.sh
install_script="$FILES"/files/install.sh
post_install_script="$FILES"/files/post-install.sh
error_script="$FILES"/files/on-error.sh
success_script="$FILES"/files/on-success.sh
cleanup_script="$FILES"/files/cleanup.sh

case "$STATE" in

    NeedsArtifactReboot)
        echo "No"
    ;;

    SupportsRollback)
        echo "Yes"
    ;;

    ArtifactInstall)
        chmod u+x "$pre_install_script"
        "$pre_install_script"

        chmod u+x "$install_script"
        "$install_script"

        chmod u+x "$post_install_script"
        "$post_install_script"
    ;;

    ArtifactCommit)
        chmod u+x "$success_script"
        "$success_script"
    ;;

    ArtifactRollback)
        chmod u+x "$error_script"
        "$error_script"
    ;;

    Cleanup)
        chmod u+x "$cleanup_script"
        "$cleanup_script"
    ;;

esac

exit 0