name: Create mender artifact
on:
    push:
        tags:
          - v[0-9]+.[0-9]+.[0-9]+
          - v[0-9]+.[0-9]+.[0-9]+-*
jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
        - name: Setup TAG
          run: echo ::set-env name=TAG::${GITHUB_REF/refs\/tags\//}

        - name: Install mender-artifact
          run: |
            wget https://d1b0l86ne08fsf.cloudfront.net/mender-artifact/3.3.0/linux/mender-artifact
            sudo mv mender-artifact /usr/local/bin/
            sudo chmod +x /usr/local/bin/mender-artifact

        - name: Download update modules
          run: |
            sudo mkdir -p /usr/share/mender/modules/v3
            sudo wget -P /usr/share/mender/modules/v3 https://raw.githubusercontent.com/mendersoftware/mender/master/support/modules/script

        - uses: actions/checkout@v1

        - name: Add Umbrel update module 
          run: |
            sudo mv update-scripts/umbrel /usr/share/mender/modules/v3/
            sudo chmod +x /usr/share/mender/modules/v3/umbrel

        - name: Create mender artifact
          run: |
            ARTIFACT_NAME="umbrel-compose-$TAG"
            DEVICE_TYPE="raspberrypi4"
            OUTPUT_PATH="umbrel-compose-$TAG.mender"
            mender-artifact write module-image \
            -T script \
            -n ${ARTIFACT_NAME} \
            -t ${DEVICE_TYPE} \
            -o ${OUTPUT_PATH} \
            -f update-scripts/test-update.sh

        - name: Release artifact
          uses: meeDamian/github-release@v1.0.0
          if: startsWith(github.ref, 'refs/tags/')
          with:
            gzip: false
            files: "*.mender"
            token: ${{ secrets.GITHUB_TOKEN }}
            allow_override: true